name: Check, Lint, Build, Test Docs Site

# run on all branches except main, where the deploy workflow runs
on:
  push:
    branches-ignore:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18]
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Check Types
        run: npm run check
      - name: Lint
        run: npm run lint
      - name: Build site
        run: npm run build
      - name: Run tests
        run: npm run test:unit
